### ISSUE TITLE
Cancel a booking before payment

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#607]
Make sure all the cancellation flows for cancelling before a payment are followed as laid out in whimsical: https://whimsical.com/fWPQBgdTuTvRsdCzFqxmc#2Ux7TurymPj6tzgvSPp3

And on Figma
https://www.figma.com/file/CMkMSsbTLjpitcetLUunz9/PressPad?node-id=1982%3A11368

To confirm, this includes any cancellations before a payment has been made. This is the simplest as admin doesn't need to involved and no money needs to be refunded.

**However** please note that if the booking involves 100% payment from organisation that counts as a payment even though the intern is not making a booking, so that would be a cancellation after payment and would be tackled in issue #611 

- [ ] Update booking pages and backend so it accepts cancellation before payment
- [ ] make sure host profile calendar works when cancelling bookings (see #615)

**Comment by dupreesi** [comment]
**Cancel before payment flows** 

1. cancelled by intern after request accepted by host but before any payment
- [ ] Host receives update and booking removed from bookings section
- [ ] Booking status in admin dashboard changed to cancelled
- [ ] Column in intern and host section of dashboard shows amount of cancellations 

2. Cancelled by intern before request accepted by host
- [ ] Host receives update and booking removed from bookings section
- [ ] Booking status in admin dashboard changed to cancelled

3. Automatically cancelled because intern did not pay within first 48 hours
- [ ] Host receives update and booking removed from bookings section
- [ ] Booking status in admin dashboard changed to cancelled
- [ ] Intern receives update that booking has been cancelled and warning message

4. Cancelled by host before intern had made payment
- [ ] Host receives update and booking removed from bookings section
- [ ] Booking status in admin dashboard changed to cancelled
- [ ] Intern receives update and booking request removed from bookings section

**TASKS** 
- [ ] Create Cancel Booking are you sure page (same design than booking view but new route)
- [ ] On success: change booking status to cancelled, remove booking from bookings of involved users
- [ ] Create Booking Cancelled Success page for cancelling party 
- [ ] Create Booking request cancelled update page for the other user type including the message provided by the cancelling party
- [ ] Update admin bookings section on dashboard to show cancelled label (no further actions required)
- [ ] Create automated cancellation success pages for intern and host (shown after 48 hours of initial booking) and change booking status accordingly
- [ ] Set up emails to be sent after booking cancellatiion before payment
- [ ] Accepted a booking request but the intern didn't pay within 48hours or cancels in this period
- [ ] Host cancels booking within this 48 hour period before payment
