### ISSUE TITLE
Cancel a booking Automaticly

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#608]
relates #616 
There are two ways a booking is cancelled automatically

1. Intern has not paid the first initial payment. This is cancelled automatically as no money has changed hands 

2. Intern has failed to make a follow payment that was due after money has already changed hands

Route 1 involves
- [x] Update booking page 

Route 2 involves
- [ ] Update booking page to show payment is due 7 days prior to payment (e.g. if a user has booked for 8 weeks, after 3 weeks they will told payment is due and be given 7 days to pay)
- [x] Update bookings page to show payment is overdue
- [x] Update booking to show as cancelled and start cancelled after payment flow (#611) if still not paid after 48 hours
- [x] Make sure this issue is complete first: https://github.com/yalla-coop/presspad/issues/611
- [x] Make sure automated email as outlined in this issue is connected (Ramy has set up these emails) https://github.com/yalla-coop/presspad/issues/536
