### ISSUE TITLE
Cancel a booking after payment

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#611]
This is if either the host or intern cancels the booking after some form of payment has been made **including** if the organisation has decided to pay 100% of the booking. Basically, if the host has received any money whatsoever into their wallet then it counts as a cancellation. 

This requires admin involvement and so is the most involved.

Make sure all the cancellation flows for cancelling before a payment are followed as laid out in whimsical: https://whimsical.com/fWPQBgdTuTvRsdCzFqxmc#2Ux7TurymPj6tzgvSPp3

And on Figma
https://www.figma.com/file/CMkMSsbTLjpitcetLUunz9/PressPad?node-id=1982%3A11368

- [x] Update booking pages for these stages
- [x] Add cancellation pages
- [x] Add admin flow to review and deal with the cancellation
- [ ] Make sure automated email as outlined in this issue is connected (Ramy has set up these emails) https://github.com/yalla-coop/presspad/issues/536

**Comment by dupreesi** [comment]
**Part 1 => handle cancelled after payment until under review flow**

- [ ] create booking view are you sure page 1 (include what’s been payed so far and if intern / host)
- [ ] create are you sure page 2 (confirming cancellation with answer requirement for intern / host)
   - [ ] create central booking cancellation are you sure text object
- [ ] update booking status -> cancelled after payment, cancellation under review: true
- [ ] show booking accordingly in admin dashboard with option to review
- [ ] create booking view cancellation request with status under review for intern / host 
   - [ ] Create central booking status texts object

**Part 2 => create review flow**

- [ ] create admin action ‚please review‘
- [ ] create review booking page 
- [ ] input booking details, user details etc
- [ ] create reason for cancelling option -> add to db
- [ ] add who is responsible for cancellation option -> add to db
- [ ] add additional notes option -> add to db

**Part 3 => create Refund flow**

- [ ] create refund section so admin can / must decide how much to allocate to each user
- [ ] add check to dis/enable organisation input if (no) coupon involved in booking
- [ ] for org back to their funds 
- [ ] for host back to host wallet 
- [ ] for presspad back to their funds 
- [ ] for intern -> create new withdraw request with option to add bank details
- [ ] Change titel of admin withdraw requests to payment requests 
- [ ] update withdraw requests model to also deal with interns (e.g. change bank details to be optional, add user type)
- [ ] show withdraw requests with option to enter bank details and mark as done

**Part 4 => create booking cancelled success flow**

- [ ] update booking status -> cancellation under review: false
- [ ] create admin option to view details of cancelled booking 
- [ ] create view details of cancelled booking page (admin)
- [ ]  create cancellation completed booking view for host and intern
- [ ] add notifications and emailing for cases under review and success
