### ISSUE TITLE
Update Admin Front End Pages

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#693]
Update all pages (except bursary and dashboard) to follow the new designs https://www.figma.com/file/CMkMSsbTLjpitcetLUunz9/PressPad?node-id=2904%3A20

Each should use the table component #649 

- [ ] For all of them check the data that is already been set up to ideally use that and then update the relevant back end issue for that page to say what extra data needs to be supplied

Pages to create
- [x] Clients - back end issue #694 
- [x] Interns - back end issue #695
- [x] Hosts - back end issue #696
- [x] Payments - back end issue #697
- [x] Bookings - back end issue #698
