### ISSUE TITLE
HOST & INTERN: send email with checklist to host and intern

### ISSUE THREAD

**Issue by FarahZaqout** [yalla-coop/presspad#98]
when the host accepts or rejects an intern stay request:
  - [x] Send an email with a checklist to the host after accepting an intern. (3 weeks, 2 weeks and 1 week before the starting date).
     - [x] Implement a CRON job to automate the sending process: [cron jobs in nodejs](https://www.npmjs.com/package/node-cron).
     - [x] the last reminder is a week before the stay and the second is 2 week before and so on, the reminders only between the acceptance day and the stay day/
  - [x] Send an email to connect the intern and the host if accepted or rejection email.
     - [x] both intern and host must be in the same email thread (CC). [how to create an email thread.](https://github.com/sendgrid/sendgrid-nodejs/issues/690).

* **Email API for now is NodeMailer. Mail transporter is currently set to google. Should be received from env variables.**
* **Current cron time is 03:00 AM.**

**Comment by FarahZaqout** [comment]
relates #49

**Comment by FarahZaqout** [comment]
will refactor database so this must await it.
